---
title: "Getting Started"
output: powerpoint_presentation
---

### Getting Started

* You can render Microsoft PowerPoint presentations from R Markdown documents. 
* This capability is made possible by recent improvements to Pandoc, which converts files from one markup format into another. 
* To use all the features of RStudio with PowerPoint output, install the RStudio Preview which bundles Pandoc 2.x. 
* You should also install the development version of rmarkdown.

### Example

```
---
output: powerpoint_presentation
---

# Section Header

## Section Header 

### Title slide
Content

#### Content Header

##### Content Header
```

### Knit

* When you knit an R Markdown document, RStudio renders your document in the PowerPoint output format. 
* If you are using RStudio Desktop, your PowerPoint presentation will automatically open and take you back to the last slide you were viewing. 
* If you are using RStudio Server, you will be prompted to download the PowerPoint presentation file.

### Command Line

You can also render files programmatically from the R console.

```

rmarkdown::render("in.Rmd", output_format = "powerpoint_presentation")
```

### Modify by Hand

* In some cases, you might want to make manual adjustments to your PowerPoint presentation after you render it. 
* Fortunately, markdown elements – such as titles, text, code, and tables – are rendered natively in PowerPoint. 
* Manually changing the slide size or design after rendering will automatically change these elements to match the new style.

### Getting Help

* [Markdown Basics](https://rmarkdown.rstudio.com/authoring_basics.html)
* [Pandoc Markdown](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)
* [R Code Chunks](https://rmarkdown.rstudio.com/authoring_rcodechunks.html)
* [Chunk Options](https://yihui.name/knitr/options/)
* [Pandoc User’s Guide](http://pandoc.org/MANUAL.html)

Submit PowerPoint issues to [rmarkdown/issues](https://github.com/rstudio/rmarkdown/issues)

