---
output: 
  powerpoint_presentation:
    slide_level: 3
---

### Slide types

1. **Title**. Defined in the YAML header.
2. **Section header**. Break the presentation into sections. These slides have a section header but no content.
3. **Title and content**. Presentation content.
4. **Two Content**. Presentation content in two columns.

### Setting the slide level

By default, the slide level is the highest header level in the hierarchy that is followed immediately by content, and not another header, somewhere in the document. Override using the `slide-level` option. For details, see *Structuring the Slide Show* in the [Pandoc Manual](http://pandoc.org/MANUAL.html).

### Rules

* A horizontal rule always starts a new slide
* A header at the slide level always starts a new slide
* Headers below the slide level in the hierarchy create headers within a slide
* Headers above the slide level in the hierarchy create *section headers*
* A title page is constructed automatically from the document’s title block

# Example

### Slide Level: 3

```
---
output: 
  powerpoint_presentation:
    slide_level: 3
---

# Section Header
By default, content here would normally set this as the slide level 

### Title and Content Slide
The override sets this as the new slide level

#### Bold text
Text
```

# Section Header
By default, content here would normally set this as the slide level 

### Title and Content Slide
The override sets this as the new slide level

#### Bold text
Text
